# Generated by Django 2.2.24 on 2023-03-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
