# Generated by Django 2.2.24 on 2023-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20230309_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
